server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    autoindex on;                    # Permite navegar el mirror como un índice

    access_log /var/log/nginx/mirror_access.log;
    error_log  /var/log/nginx/mirror_error.log;

    location / {
        try_files $uri $uri/ =404;
    }
}
